### PR TITLE
First pass at breaking up the code into modules. 

### PR DESCRIPTION
**Pull request by murrayju**
Lots of cleanup as well

### CODE REVIEW

**Comment by elju** [comment]
are all those xml files stuff related to your IDE?

**Comment by murrayju** [comment]
@elju yeah. Useful for anyone using webstorm. They don't change often.

**Comment by mynameisfiber** [comment]
looks purdy

**Comment by murrayju** [comment]
we can probably break it up even further. For example, I put all of the directives into one file, but we could instead group those somehow into several.

**Comment by elju** [comment]
:shipit: :ship: :shipit: :ship: :shipit: :ship: :shipit: :ship: :shipit: :ship:

**Pull request merged**
